Return error if adding a package fails.
u-root/gobusybox pull request #73
Opened 2022-06-06 16:46 UTC by Prabhuk

Current behavior allows for the build to continue if adding a package fails. Modifying the behavior to fail fast to identify the build failures.

2022-06-06 16:54 UTC, 10000TB approved these changes

2022-06-08 21:57 UTC, hugelgupf approved these changes

2022-06-08 21:57 UTC, hugelgupf requested changes

2022-06-08 21:57 UTC, hugelgupf commented on src/pkg/bb/findpkg/bb.go
> +		return plist, fmt.Errorf("Failed to add package %v for errors:", p)
go readability: lower case error messages "failed"

2022-06-08 22:22 UTC, Prabhuk commented on src/pkg/bb/findpkg/bb.go
> +		return plist, fmt.Errorf("Failed to add package %v for errors:", p)
Done. PTAL

2022-06-08 22:50 UTC, hugelgupf approved these changes

2022-06-08 22:51 UTC, merged